### ISSUE TITLE
I don't know where to put the submod and lib folders.

### ISSUE THREAD

**Issue by xChilXChilx** [tw4449/tw4449-Custom-Room-Selection-Pack-Main-Repository#6]
I'm on mac and I don't see a folder that has DDLC.exe since I was on mac, I was then told to go put it in the folder where DDLC.app is but I also can't find a folder that has DDLC.app. :/

**Comment by multimokia** [comment]
How are you launching MAS?

**Comment by xChilXChilx** [comment]
I don't understand that. ;-;

**Comment by multimokia** [comment]
To actually open MAS and see Monika, what do you do?

**Comment by xChilXChilx** [comment]
I just click on the app.

**Comment by d3adpan** [comment]
Hey there, perhaps try navigating to the following folder and dropping the files there?
Firstly of course, shut down MAS.  Then go to:

DDLC.app/Contents/Resources/autorun

In that folder you should see your "game" folder, "characters", "renpy" and etc.  Drop the contents of the submod into the autorun folder so that the submod's folders are merged with the existing "game" and "lib" folders.

Then restart and hopefully you and your Monika will be able to access the new locations.

**Comment by xChilXChilx** [comment]
Ok! I'll try that.

**Comment by multimokia** [comment]
Yeah that app is the `DDLC.app`, which you should also be able to enter as a folder

**Comment by xChilXChilx** [comment]
TYSM! IT WORKED!!

**Comment by d3adpan** [comment]
Awesome, thanks for reporting back!
Enjoy :)
